# Generated by Django 4.0.2 on 2022-02-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginrischest', '0004_cartitem_user_order_user_orderitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ZIP_Code',
            new_name='post_code',
        ),
        migrations.AddField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_order',
            field=models.PositiveIntegerField(choices=[(0, 'รอการจัดส่ง'), (1, 'อยู่ระหว่างการจัดส่ง'), (2, 'จัดส่งสำเร็จ'), (3, 'จัดส่งไม่สำเร็จ'), (4, 'ยกเลิกการจัดส่ง')], default=0),
        ),
    ]
