# Generated by Django 4.0.2 on 2022-02-11 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginrischest', '0005_rename_zip_code_order_post_code_order_date_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated',
        ),
    ]
