# Generated by Django 4.0.2 on 2022-02-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginrischest', '0007_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255, null=True)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'ยอดขายทีม',
                'verbose_name_plural': 'ข้อมูลยอดขายทีม',
                'db_table': 'income_team',
                'managed': True,
            },
        ),
    ]
