# Generated by Django 4.0.2 on 2022-02-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginrischest', '0009_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cart',
            field=models.ManyToManyField(to='loginrischest.CartItem'),
        ),
    ]
