# Generated by Django 4.0.2 on 2022-02-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginrischest', '0010_remove_orderitem_product_orderitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='choose_delivery',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
