# Generated by Django 4.0.2 on 2022-02-07 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'ข้อมูลหลัก',
                'verbose_name_plural': 'ข้อมูลหลัก',
                'db_table': 'Base',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_package', models.FileField(blank=True, upload_to='package')),
                ('image_package2', models.FileField(blank=True, null=True, upload_to='package2')),
                ('name_package', models.CharField(max_length=255, null=True)),
                ('price_package', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('bodytext', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'แพคเกจ',
                'verbose_name_plural': 'ข้อมูลแพคเกจ',
                'db_table': 'Package',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recommender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('นาย', 'นาย'), ('นางสาว', 'นางสาว'), ('นาง', 'นาง')], max_length=100, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tel', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(choices=[(None, 'รอการอนุมัติ'), (True, 'อนุมัติ'), (False, 'ไม่อนุมัติ')], default=None, null=True)),
            ],
            options={
                'verbose_name': 'ชื่อ',
                'verbose_name_plural': 'ผู้แนะนำ',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('package', models.CharField(choices=[('Diamond', 'Diamond'), ('Silver', 'Silver'), ('VIP', 'VIP')], max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('zone', models.CharField(max_length=255, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('province', models.CharField(max_length=255, null=True)),
                ('ZIP_code', models.CharField(max_length=5, null=True)),
                ('choose_delivery', models.CharField(max_length=255, null=True)),
                ('total_delivery', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'ที่อยู่จัดส่ง',
                'verbose_name_plural': 'ที่อยู่จัดส่ง',
                'db_table': 'address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('นาย', 'นาย'), ('นางสาว', 'นางสาว'), ('นาง', 'นาง')], max_length=100, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('useremail', models.CharField(max_length=255, null=True)),
                ('package', models.CharField(choices=[('Diamond', 'Diamond'), ('Silver', 'Silver'), ('VIP', 'VIP')], max_length=255, null=True)),
                ('accountname', models.CharField(max_length=255)),
                ('accountnumber', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=255, null=True)),
                ('recommender', models.CharField(max_length=255, null=True)),
                ('recommen', models.CharField(max_length=255, null=True)),
                ('bank', models.CharField(choices=[('ธนาคารกรุงเทพ', 'ธนาคารกรุงเทพ'), ('ธนาคารกรุงไทย', 'ธนาคารกรุงไทย'), ('ธนาคารกรุงศรีอยุธยา', 'ธนาคารกรุงศรีอยุธยา'), ('ธนาคารกสิกรไทย', 'ธนาคารกสิกรไทย'), ('ธนาคารเกียรตินาคินภัทร', 'ธนาคารเกียรตินาคินภัทร'), ('ธนาคารทหารไทยธนชาต', 'ธนาคารทหารไทยธนชาต'), ('ธนาคารไทยพาณิชย์', 'ธนาคารไทยพาณิชย์'), ('ธนาคารยูโอบี', 'ธนาคารยูโอบี'), ('ธนาคารอิสลามแห่งประเทศไทย', 'ธนาคารอิสลามแห่งประเทศไทย'), ('ธนาคารออมสิน', 'ธนาคารออมสิน')], max_length=255, null=True)),
                ('image_id_card', models.FileField(blank=True, upload_to='id_card')),
                ('image_bank_account', models.FileField(blank=True, upload_to='bankaccount')),
                ('image_slip', models.FileField(blank=True, upload_to='slip')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status_member', models.BooleanField(choices=[(None, 'รอการอนุมัติ'), (True, 'อนุมัติ'), (False, 'ไม่อนุมัติ')], default=None, null=True)),
                ('address', models.TextField(null=True)),
                ('zone', models.CharField(max_length=255, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('province', models.CharField(max_length=255, null=True)),
                ('ZIP_code', models.CharField(max_length=5, null=True)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'สมาชิก',
                'verbose_name_plural': 'ข้อมูลสมาชิก',
                'db_table': 'member',
                'managed': True,
            },
        ),
    ]
