# Generated by Django 4.0.2 on 2022-02-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homerischest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, upload_to='slideshow')),
                ('name_img', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'สไลด์โชว์',
                'verbose_name_plural': 'ข้อมูลสไลด์โชว์',
                'db_table': 'Slideshow',
                'managed': True,
            },
        ),
    ]
